import { PERMISSIONS } from "./auth.enum";

export const despachoPermissions = [
        PERMISSIONS.DESPACHO_READ,
        PERMISSIONS.DESPACHO_UPDATE,
        PERMISSIONS.DESPACHO_FINANCE,

        PERMISSIONS.CONTRIBUYENTE_CREATE,
        PERMISSIONS.CONTRIBUYENTE_READ,
        PERMISSIONS.CONTRIBUYENTE_UPDATE,
        PERMISSIONS.CONTRIBUYENTE_FINANCE,
        PERMISSIONS.CONTRIBUYENTE_DELETE,

        PERMISSIONS.FACTURA_READ,

        PERMISSIONS.PRODUCTO_CREATE,
        PERMISSIONS.PRODUCTO_UPDATE,

        PERMISSIONS.TAREA_READ,
        PERMISSIONS.TAREA_CREATE,
        PERMISSIONS.TAREA_UPDATE,
        PERMISSIONS.TAREA_DELETE,

        PERMISSIONS.COTIZACION_READ,
        PERMISSIONS.COTIZACION_CREATE,
        PERMISSIONS.COTIZACION_UPDATE,
        PERMISSIONS.COTIZACION_DELETE,

        PERMISSIONS.CLIENTE_CREATE,

        PERMISSIONS.CATALOGO_READ,
        PERMISSIONS.CATALOGO_CREATE,
        PERMISSIONS.CATALOGO_UPDATE,
        PERMISSIONS.CATALOGO_DELETE,

        PERMISSIONS.LOG_READ
    ];

export const contribuyentePermissions = [
        PERMISSIONS.DESPACHO_READ,

        PERMISSIONS.CONTRIBUYENTE_READ,
        PERMISSIONS.CONTRIBUYENTE_UPDATE,
        PERMISSIONS.CONTRIBUYENTE_FINANCE,

        PERMISSIONS.AUXILIAR_CREATE,
        PERMISSIONS.AUXILIAR_READ,
        PERMISSIONS.AUXILIAR_UPDATE,
        PERMISSIONS.AUXILIAR_DELETE,

        PERMISSIONS.FACTURA_READ,
        PERMISSIONS.FACTURA_CREATE,
        PERMISSIONS.FACTURA_UPDATE,
        PERMISSIONS.FACTURA_DELETE,

        PERMISSIONS.PRODUCTO_READ,
        PERMISSIONS.PRODUCTO_CREATE,
        PERMISSIONS.PRODUCTO_UPDATE,
        PERMISSIONS.PRODUCTO_DELETE,

        PERMISSIONS.TAREA_READ,
        PERMISSIONS.TAREA_CREATE,
        PERMISSIONS.TAREA_UPDATE,

        PERMISSIONS.PROVEEDOR_READ,
        PERMISSIONS.PROVEEDOR_CREATE,
        PERMISSIONS.PROVEEDOR_UPDATE,
        PERMISSIONS.PROVEEDOR_DELETE,

        PERMISSIONS.COTIZACION_READ,
        PERMISSIONS.COTIZACION_CREATE,
        PERMISSIONS.COTIZACION_UPDATE,
        PERMISSIONS.COTIZACION_DELETE,

        PERMISSIONS.CLIENTE_READ,
        PERMISSIONS.CLIENTE_CREATE,
        PERMISSIONS.CLIENTE_UPDATE,
        PERMISSIONS.CLIENTE_DELETE,

        PERMISSIONS.LOG_READ
    ];

export const auxiliarPermissions = [
        PERMISSIONS.AUXILIAR_READ,
        PERMISSIONS.AUXILIAR_UPDATE,

        PERMISSIONS.TAREA_READ,
        PERMISSIONS.TAREA_UPDATE,
    ];